"""make_account_id_nullable_for_global_knowledge

Revision ID: 260b0d402781
Revises: f3f9be4a991b
Create Date: 2026-07-20 14:18:09.298513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260b0d402781'
down_revision: Union[str, Sequence[str], None] = 'f3f9be4a991b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['account_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('account_documents', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('account_embeddings', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.alter_column('account_embeddings', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'account_embeddings', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_embeddings', type_='foreignkey')
    op.alter_column('account_embeddings', 'account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('account_embeddings', 'workspace_id')
    op.alter_column('account_documents', 'account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('account_document_chunks')
    # ### end Alembic commands ###
